// Code generated by "stringer -type=Symbol"; DO NOT EDIT.

package deck

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[Spades-1]
	_ = x[Diamonds-2]
	_ = x[Clubs-3]
	_ = x[Hearts-4]
}

const _Symbol_name = "NoneSpadesDiamondsClubsHearts"

var _Symbol_index = [...]uint8{0, 4, 10, 18, 23, 29}

func (i Symbol) String() string {
	if i < 0 || i >= Symbol(len(_Symbol_index)-1) {
		return "Symbol(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Symbol_name[_Symbol_index[i]:_Symbol_index[i+1]]
}
