name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup go and stringer
      - name: Set up Go
        uses: actions/setup-go@v2
      - run: echo "::set-env name=PATH::$(go env GOPATH)/bin:$PATH"
      - run: go get -v golang.org/x/tools/cmd/stringer
        with:
          go-version: 1.17

      - name: Generate
        run: go generate -v ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
